### ISSUE TITLE
Can't find docker .env file

### ISSUE THREAD

**Issue by kaffeocigg** [EnvelopSound/Earshot#17]
Hi! Thanks for this package! 

When I run **docker-compose up --build nginx-rtmp** I get **ERROR: Couldn't find env file: /Users/anton/Documents/Earshot/.env**

I have downloaded docker, git and git LFS, then I do git clone, then I cd into Earshot and run the command. Any ideas?

**Comment by roddylindsay** [comment]
Hi @kaffeocigg : we just updated the README to specify that you should copy the .env.example file to .env .  Can you try again?

**Comment by kaffeocigg** [comment]
This solved it! : D Thank you!
