### ISSUE TITLE
Cannot start Earshot

### ISSUE THREAD

**Issue by kaffeocigg** [EnvelopSound/Earshot#18]
I seem to have run into another issue. After I created the environment settings, nginx says it cannot start Earshot. Here's a copy of the last rows: 

**Successfully built 4d65ee1ef18849cfda1b594b1e9402f51f45f642f1e64b6e2249e4daa0d3190e
Creating earshot_nginx-rtmp_1 ... done
Attaching to earshot_nginx-rtmp_1
nginx-rtmp_1   | Cannot start Earshot
nginx-rtmp_1   | Please make sure you have configured your environment correctly.
nginx-rtmp_1   | The following environment variable was not set: DOMAIN
nginx-rtmp_1   | ./nginx-letsencrypt: exit: line 11: Illegal number: -1
earshot_nginx-rtmp_1 exited with code 2**

Ran a test configuration of nginx and it says that everything is OK: 

**nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful**

I tried starting the stream in OBS with the custom server, but it says it fails to connect to the server. 

Do you have any ideas of how to proceed? :)

**Comment by roddylindsay** [comment]
Hi @kaffeocigg : some of the env var stuff was cleaned up with better error messaging.  Can you pull down the latest code on master and try again?

**Comment by kaffeocigg** [comment]
Great work, the error message has disappeared and the program starts!
